## Takes the sequence table generated by DADA2 (seqtab_nochim) and creates an
## OTU table as would be generated by OTU clustering

library(tibble)
library(DECIPHER)
library(Biostrings)

nproc <- 4 # set to number of cpus/processors to use for the clustering
asv_sequences <- colnames(seqtab_nochim)
sample_names <- rownames(seqtab_nochim)
dna <- Biostrings::DNAStringSet(asv_sequences)
d <- DECIPHER::DistanceMatrix(aln, processors = nproc)
aln <- DECIPHER::AlignSeqs(dna, processors = nproc)
d <- DECIPHER::DistanceMatrix(aln, processors = nproc)
clusters <- DECIPHER::IdClusters(
  d, 
  method = "complete",
  cutoff = 0.15, # use `cutoff = 0.15` for a 85% OTU 
  processors = nproc)
clusters <- clusters %>%
  add_column(sequence = asv_sequences)
seqtab_clustered <- seqtab_nochim %>% 
  t %>%
  rowsum(clusters$cluster) %>%
  t
# Optional renaming of clusters to OTU<cluster #>
colnames(seqtab_clustered) <- paste0("OTU", colnames(seqtab_clustered))
save(clusters, file = "./otu_clusters.RData")